name: 'Test issue'
on: [push]
concurrency:
  group: ${{ github.workflow }}
jobs:
  test-brew-failure:
    name: 'Test Brew failure'
    runs-on: macos-11
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v3

    - name: 'Brew issue steps'
      run: |
        brew config
        brew doctor
        brew update

    - name: 'Make tarball'
      run: |
        tar czvf src.tar.gz *

    - name: 'Build formula'
      env:
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        sed -i '' "s#/Users/brucecollie/code/scratch/repro#$(pwd)#" Formula/demo.rb
        brew install ./Formula/demo.rb --verbose # --with-llvm

  test-brew-success:
    name: 'Test Brew success'
    runs-on: macos-11
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v3

    - name: 'Make tarball'
      run: |
        tar czvf src.tar.gz *

    - name: 'Build formula'
      run: |
        sed -i '' "s#/Users/brucecollie/code/scratch/repro#$(pwd)#" Formula/demo.rb
        brew install ./Formula/demo.rb --verbose
