name: 'Test issue'
on: [push]
concurrency:
  group: ${{ github.workflow }}
jobs:
  test-brew-failure:
    name: 'Test Brew failure'
    runs-on: macos-11
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v3

    - name: 'Build formula'
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
        HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      run: |
        sed -i '' "s#/Users/brucecollie/code/scratch/repro#$(pwd)#" Formula/demo.rb
        cat Formula/demo.rb
